export const maps = [
  [
    'hyyyyyyyyyyj',
    'v] 8      lv',
    'v  ,,  9]  v',
    'v q   99   v',
    'v  k  99,  v',
    'v  .  999] v',
    'v8    79999v',
    'zyyyyyyyyyyu',
  ],
  [
    'hyyyyyyyyyyj',
    'v          v',
    'v          v',
    'v          v',
    'v          v',
    'v          v',
    'v          v',
    'zyyyyyyyyyyu',
  ],
]

export const mapConfig = {
  width: 32,
  height: 32,
  'a': () => [sprite('wall-left'), area(), 'wall'],
  'b': () =>  [sprite('wall-right'), area(), 'wall'],
  'c': () =>  [sprite('wall-top'), area(), 'wall'],
  'd': () =>  [sprite('wall-top-left'), area(), 'wall'],
  'e': () =>  [sprite('wall-top-right'), area(), 'wall'],
  'f': () =>  [sprite('wall-bottom-left'), area(), 'wall'],
  'g': () =>  [sprite('wall-bottom-right'), area(), 'wall'],
  'm': () =>  [sprite('fence-right-end'), area(), 'wall'],
  's': () =>  [sprite('fence-top-end'), area(), 'wall'],
  'h': () =>  [sprite('fence-top-left'), area(), 'wall'],
  'j': () =>  [sprite('fence-top-right'), area(), 'wall'],
  'v': () =>  [sprite('fence-left-connect'), area(), 'wall'],
  'x': () =>  [sprite('fence-1'), area(),  'wall'],
  'y': () =>  [sprite('fence-middle-connect'), area(),'wall'],
  'z': () =>  [sprite('fence-bottom-left'), area(), 'wall'],
  'u': () =>  [sprite('fence-bottom-right'), area(), 'wall'],
  ']': () =>  [sprite('tall-grass-1'), area()],
  '[': () =>  [sprite('tall-grass-2')],
  '.': () =>  [sprite('flower-1')],
  ',': () =>  [sprite('flower-2')],
  '-': () =>  [sprite('flower-3')],
  '^': () =>  [sprite('tree-1'), area(), 'wall'],
  '´': () =>  [sprite('tree-2'), area(),'wall'],
  '`': () =>  [sprite('tree-3'), area(), 'wall'],
  '2': () =>  [sprite('tree-5'), area(),'wall'],
  '{': () =>  [sprite('mushroom-1')],
  '1': () =>  [sprite('grass-2')],
  '9': () =>  [sprite('floor-1')],
  '8': () =>  [sprite('bucket')],
  '7': () =>  [sprite('wood-pile'), area(), 'wall'],
  'q': () =>  [sprite('wood-cut'), area(), 'wall'],
  'l': () =>  [sprite('teddy'), area(), 'teddy'],
  'k': () =>  [sprite('pumpkin')],
}